<?php

/**
 * Implementation of hook_menu().
 */
function coldsleep_hooker_menu() {
  /*$items['pricing'] = array(
    'title' => t('Pricing'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('coldsleep_hooker_member_form'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/coldsleep_hooker.pages.inc',
  );*/
  $items['admin/config/content/pricing'] = array(
    'title' => t('Pricing settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('coldsleep_hooker_pricing_form'),
    'access arguments' => array('administer nodes'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/coldsleep_hooker.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_node_view().
 */
function coldsleep_hooker_node_view($node, $view_mode, $langcode) {
  if ($node->nid == 13) {
    drupal_add_js(drupal_get_path('module', 'coldsleep_hooker') .'/js/pricing.js');
  }
}
